### ISSUE TITLE
3.0.1 to 3.3 compat

### ISSUE THREAD

**Issue by plaguedbypenguins** [01org/psm#2]
Hi,

we updated a couple of nodes to centos 6.7 on our infinipath cluster and found that MPI doesn't work between the centos 6.6 and centos 6.7 nodes.

the error is (via openmpi 1.8.3):
  PSM EP connect error (Incompatible PSM version)

centos/rhel 6.6 is infinipath-psm-3.0.1-115.1015_open.2.el6.x86_64
centos/rhel 6.7 is infinipath-psm-3.3-0.4.git6f42cdb_open.el6.x86_64

MPI works again if I downgrade the infinipath-psm package (3.3) to the centos 6.6 version (3.0.1).

our hardware is x86_64 intel with
  01:00.0 InfiniBand: QLogic Corp. IBA7322 QDR InfiniBand HCA (rev 02)

is this a known issue?
maybe 2b70a0f379c1a72b924bc4d5cf6ea19749c0bd57 fixed this compat problem?

cheers,
robin

**Comment by plaguedbypenguins** [comment]
FYI I tested this HEAD against 3.0.1 and the compat/interop problem still exists.

cheers,
robin

**Comment by hestela** [comment]
Hi @plaguedbypenguins,
I took a look at the function psmi_verno_isinteroperable() at https://github.com/01org/psm/blob/ca75825/psm.c#l87 
The psm version from 3.0.1 is 0x10e, the version from 3.3 and on is 0x10f.
These versions are not compatible according to the comment for the version in 3.3.
There was a change in the packet header.
The incombatible error from PSM is being reported by this function.
