### ISSUE TITLE
W: shlib-with-executable-stack

### ISSUE THREAD

**Issue by rfehren** [01org/psm#3]
Lintian produced the following warning after building Debian packages of infinipath-psm-3.3-7_g05f6f14_open:

    W: libpsm-infinipath1: shlib-with-executable-stack usr/lib/x86_64-linux-gnu/libinfinipath.so.4.0

Here is a more detailed explanation of the warning:

    The listed shared libraries declares the stack as executable.

    Executable stack is usually an error as it is only needed if the code
    contains GCC trampolines or similar constructs which uses code on the
    stack. One possible source for false positives are object files built
    from assembler files which don't define a proper .note.GNU-stack
    section.

    To see the permissions on the stack, run readelf -l on the shared
    library and look for the program header of type GNU_STACK. In the flag
    column, there should not be an E flag set.

    Severity: normal, Certainty: possible

I don't understand potential implications of this warning but they are quite rare, so it would be nice if someone would look into this and advise if it can be ignored. More information can be found on at:

http://lintian.debian.org/tags/shlib-with-executable-stack.html

**Comment by hestela** [comment]
@rfehren, I'll take a look at this; we did get a PR in the psm lib for the next generation product 01org/opa-psm2/pull/2 . if its that simple, i'll check internally about getting it incorporated.

**Comment by hestela** [comment]
apparently it was as simple as adding the same change, i was able to get rid of the E flag reported by readelf -l

**Comment by rfehren** [comment]
Thanks for looking into this so quickly. Seems indeed that the mentioned fix at https://github.com/michich/opa-psm2/commit/619b42357a3743c9d3d006d7cc7b57d6a45f033c would be the right thing to do here as well.

**Comment by hestela** [comment]
How are you building the debian packages? are you using alien? just wanted to be able to reproduce in house to make sure the lintian error goes away.

**Comment by rfehren** [comment]
You need a debian testing or possibly jessie system or chroot.
If you then checkout the branch debian/master from https://github.com/Q-Leap-Networks/debian-infinipath-psm you can execute
'''
dpkg-buildpackage -b -us -uc
'''
Beware however that in this branch the patches I made a pull request for will be applied before the build starts. So in order to see the error, you'll have to comment out the patches in debian/patches/series.

**Comment by hestela** [comment]
ok, adding the fix from michich/opa-psm2@619b423 does remove the lintian warning when i tested in jessie in docker. When i can get write permissions i'll make a PR and merge it.

**Comment by rfehren** [comment]
Great, thanks.
