### ISSUE TITLE
misleading indentation

### ISSUE THREAD

**Issue by HonggangLI** [01org/psm#7]
gcc   -Wall -Werror  -fpic -fPIC -D_GNU_SOURCE -funwind-tables   -O3 -g3  -Wno-strict-aliasing -DNVALGRIND -I. -I/home/honli/upstream/psm/include -I/home/honli/upstream/psm/mpspawn -I/home/honli/upstream/psm/include/linux-x86_64  -c ptl_ips/ips_opp_path_rec.c -o ptl_ips/ips_opp_path_rec.o
gcc   -Wall -Werror  -fpic -fPIC -D_GNU_SOURCE -funwind-tables   -O3 -g3  -Wno-strict-aliasing -DNVALGRIND -I. -I/home/honli/upstream/psm/include -I/home/honli/upstream/psm/mpspawn -I/home/honli/upstream/psm/include/linux-x86_64  -c psm_diags.c -o psm_diags.o
psm_diags.c: In function ‘memcpy_check_size’:
psm_diags.c:284:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation

]
     if (src == NULL || dst == NULL)
     ^~
psm_diags.c:286:7: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
       if (dst) psmi_free(dst);
       ^~
cc1: all warnings being treated as errors
Makefile:282: recipe for target 'psm_diags.o' failed
make[1]: *** [psm_diags.o] Error 1
make[1]: Leaving directory '/home/honli/upstream/psm'
Makefile:154: recipe for target 'libs' failed
make: *** [libs] Error 2

====================================
diff --git a/psm_diags.c b/psm_diags.c
index 3e2df9d..3714cea 100644
--- a/psm_diags.c
+++ b/psm_diags.c
@@ -281,10 +281,11 @@ memcpy_check_size (memcpy_fn_t fn, int *p, int *f, size_t n)
   if (USE_MALLOC) {
     src = psmi_malloc(PSMI_EP_NONE, UNDEFINED, size);
     dst = psmi_malloc(PSMI_EP_NONE, UNDEFINED, size);
-    if (src == NULL || dst == NULL) 
+    if (src == NULL || dst == NULL) {
       if (src) psmi_free(src);
       if (dst) psmi_free(dst);
       return -1;
+    }
   }
   else {
     void *src_p = NULL, *dst_p = NULL;
====================================

This simple patch fixes this issue. Please apply it. Thanks.

**Comment by jamespharvey20** [comment]
Patch unapplied.  Otherwise causes error on gcc 6.1.1.

**Comment by hestela** [comment]
fixed by 01org/psm#12
